//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShipClient.BattleShipServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="shipPlacement", Namespace="http://schemas.datacontract.org/2004/07/BattleShipService")]
    [System.SerializableAttribute()]
    public partial struct shipPlacement : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlaceMode placementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlaceMode placement {
            get {
                return this.placementField;
            }
            set {
                if ((this.placementField.Equals(value) != true)) {
                    this.placementField = value;
                    this.RaisePropertyChanged("placement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaceMode", Namespace="http://schemas.datacontract.org/2004/07/BattleShipService")]
    public enum PlaceMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VBoat = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VDestroyer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VSubmarine = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VBattleship = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VCarrier = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HBoat = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HDestroyer = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HSubmarine = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HBattleship = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HCarrier = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BattleShipServer.IServer")]
    public interface IServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServer/SetName", ReplyAction="http://tempuri.org/IServer/SetNameResponse")]
        bool SetName(int uid, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServer/Shoot", ReplyAction="http://tempuri.org/IServer/ShootResponse")]
        bool Shoot(int uid, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServer/PlaceShip", ReplyAction="http://tempuri.org/IServer/PlaceShipResponse")]
        bool PlaceShip(int uid, shipPlacement shipPlacement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServer/StartGame", ReplyAction="http://tempuri.org/IServer/StartGameResponse")]
        void StartGame(int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServer/connect", ReplyAction="http://tempuri.org/IServer/connectResponse")]
        int connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServer/GetPlayerInfo", ReplyAction="http://tempuri.org/IServer/GetPlayerInfoResponse")]
        string GetPlayerInfo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerChannel : IServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerClient : System.ServiceModel.ClientBase<IServer>, IServer {
        
        public ServerClient() {
        }
        
        public ServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SetName(int uid, string Name) {
            return base.Channel.SetName(uid, Name);
        }
        
        public bool Shoot(int uid, int x, int y) {
            return base.Channel.Shoot(uid, x, y);
        }
        
        public bool PlaceShip(int uid, shipPlacement shipPlacement) {
            return base.Channel.PlaceShip(uid, shipPlacement);
        }
        
        public void StartGame(int uid) {
            base.Channel.StartGame(uid);
        }
        
        public int connect() {
            return base.Channel.connect();
        }
        
        public string GetPlayerInfo() {
            return base.Channel.GetPlayerInfo();
        }
    }
}
